### ISSUE TITLE
Usare i ; per separare gli elementi delle liste

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/tesiguarrera#15]
Nell'elenco numerato nella sezione 1.3, poichè esso è introdotto da : è necessario concludere gli elementi dell'elenco con  ; o con , e usare il . solo per l'ultimo elemento.

**Comment by cristianolongo** [comment]
Farlo per tutti gli elenchi introdotti da : ad esempio quelli in 1° versione di GPL e 3° versione di GPL

**Comment by Alex9090** [comment]
Per caso devo separare con ; tutte le liste indicizzate con i numeri?
