### ISSUE TITLE
Inserire riferimenti ai formati

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/tesiguarrera#49]
In 4.1 Formati, nell'elenco dei formati aperti è necessario indicare per ogni formato una entry bibliografica o una uri per ottenere la specifica del formato.

**Comment by Alex9090** [comment]
Sto mettendo delle note a piè di pagina. Vanno bene, oppure uso la URI

**Comment by cristianolongo** [comment]
Metterle come note a piè di pagina
