### ISSUE TITLE
Classificazione a 5 stelle

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/tesiguarrera#61]
Riscrivere il primo paragrafo della sezione 4.3 come segue

"Per distinguere i vari formati in cui vengono fornite le collezioni di dati, il W3C le classifica in base alle loro caratteristiche, assegnandoli delle stelle, che vanno da 1 a 5."

**Comment by Alex9090** [comment]
Ma io ho riscritto come mi avevi messo all'inizio.

**Comment by cristianolongo** [comment]
Giusto, solo

"assegnandoli" -> "assegnandogli"
