### ISSUE TITLE
Spiegare a cosa servono i metadati

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/tesiguarrera#66]
Nella sezione 4.4 METADATI spiegare perchè sono utili i  metadati nel nostro contesto.

**Comment by Alex9090** [comment]
Ho spiegato ciò in un paragrafo che ho aggiunto, il 4.4.7 "Perchè i metadati sono utili"

**Comment by cristianolongo** [comment]
NOn è necessario creare un sottoparagrafo a se stante. Quella parte va messa nella introduzione della sezione sui metadati
