### ISSUE TITLE
Organizzazione capitolo sugli aspetti legali

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/tesiguarrera#8]
Proporre una struttura per questo capitolo e organizzarlo in maniera che le varie parti siano consequenziali l'una all'altra. Connettere ogni parte con la succesiva.

**Comment by Alex9090** [comment]
Ho indicizzato i sotto capitoli di questo capitolo più grande. Però alla fine ognuno di questi sottocapitoli parla di una differente problema che diciamo si collega con tutti alla fine. Comunque, ne parliamo meglio quando ci sentiamo, per il resto le altre issue le ho risolte e ho committato.

**Comment by cristianolongo** [comment]
Proporrei di cambiare il titolo in "Aspetti Legali e Amministrativi"

**Comment by cristianolongo** [comment]
inserire nella introduzione del capitolo un paragrafo che descrive la struttura del capitolo. Una cosa del tipo "Nella Sezione X parleremo dell'infrastruttura legislativa, riportando ed esaminando gli articolo del Codice dell'Amministrazione Digitale di interesse per gli ope data. Nella Sezione (X+1) ..."
